### ISSUE TITLE
Can changes on master directly publish to the production script on cloudflare?

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding#8]
does https://github.com/cloudflare/wrangler-action apply to us cc @rudietuesdays @jheretic

**Comment by rudietuesdays** [comment]
I believe we could set this up (but defer to @jheretic to confirm). Not sure what we'd use it for though, since updates in Notion should be reflected on the Super site as they go live. I don't believe this would apply to the import script either; we'd likely use a CF worker for that but I don't think like this.

**Comment by danblah** [comment]
Yeah, closing this... not relevant while we're not using the cf worker method.
